# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/4-devops/TourOfHeroes/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'TourOfHeroesSonarCloud'
    organization: '210215-usf-net'
    scannerMode: 'MSBuild'
    projectKey: '210215-USF-NET_trainer-code'
    projectName: 'trainer-code'
- task: DotNetCoreCLI@2
  displayName: build 
  inputs:
    command: 'build'
    projects: '**/4-devops/TourOfHeroes/*.sln'

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: 'test'
    projects: '**/4-devops/TourOfHeroes/ToHTests/*.csproj'
    arguments: --configuration $(buildConfiguration) --collect "Code Coverage"
- task: PublishCodeCoverageResults@1
  displayName: publish code coverage results
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/coburtura/coverage.xml'
- task: SonarCloudAnalyze@1
  displayName: run code analysis

- task: SonarCloudPublish@1
  displayName: publish code analysis
- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: true
    projects: '**/4-devops/TourOfHeroes/ToHMVC/*.csproj'

- task: AzureRmWebAppDeployment@4
  displayName: deploy
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'TourOfHeroesAzure'
    appType: 'webApp'
    WebAppName: 'tourofheroesmvc'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'




